### ISSUE TITLE
Compiling on Linux Mint and Raspbian (maybe others) fails

### ISSUE THREAD

**Issue by aligator** [joysfera/parcp#1]
But I got it working with two little changes:
parcp-usb.c:
`#include <HIDAPI/hidapi.h>`
to
`#include <hidapi/hidapi.h>`

and 
Makefile.linux:
`LIB_USB = -L/home/joy/Qt/HIDAPI/libusb -lHIDAPI -lusb-1.0`
to
`LIB_USB = -lhidapi-libusb -lusb-1.0`

On both systems I did 
`sudo apt-get install libusb-1.0-0-dev libhidapi-dev`

**Comment by joysfera** [comment]
fixed by #2
