### ISSUE TITLE
Cannot get DOS version to work

### ISSUE THREAD

**Issue by aligator** [joysfera/parcp#3]
Hi,
I use PARCP with the USB adapter. From Atari to linux it works great, but from DOS to linux not.

I tried it first with a Compaq DOS laptop, however I get the error
```
Server's Debug info: expected $4853, received $ffff
```
Then I remembered that I have a SyQuest driver installed.
Disabling it did not help.

Then I tried to run it from a basic DOS starting floppy:
* created a new DOS Starting floppy from Win XP floppy format dialog.
* Copied over parcp to it together with CWSDPMI exe files, which seem to be required
* started the laptop with that floppy, so no other driver should be loaded. -> Same error

Then I booted that same floppy with another xp-machine (regenerated the parcpcfg of course) and got the same error there also.

It doesn't matter on which side I start the client/server.

Anything else I could try?

**Comment by joysfera** [comment]
On the Compaq is it PARCP v3.90?

Also, did you set up the printer port mode correctly in PC BIOS? There are three different modes of operation:
https://joy.sophics.cz/parcp/parcpdoc.htm#Features2

Have you tried running PARCPCFG.EXE?
https://joy.sophics.cz/parcp/parcpdoc.htm#Installation5

Did you set the port type, port address and cable type correctly?

**Comment by aligator** [comment]
> On the Compaq is it PARCP v3.90?

Yes, I used the newest version on all machines.

> Also, did you set up the printer port mode correctly in PC BIOS? There are three different modes of operation

Did not try that yet.

> Have you tried running PARCPCFG.EXE?

Yes, it should be correct what I used.

As I broke the Compaq, I cannot test anymore with it until I fix that, only with the xp-machine I can still test.

**Comment by joysfera** [comment]
Other users confirmed recently that PARCP v3.90 still works like a charm on pre-historic DOS machines.
