### ISSUE TITLE
Client for old XT computers?

### ISSUE THREAD

**Issue by jedie** [joysfera/parcp#4]
PARCP needs currently a 386... Would be great if it's useable on a XT with only 512KB RAM.

Any idea if this is possible?!?

**Comment by joysfera** [comment]
On So, 2021-10-09 at 01:04 -0700, Jens Diemer wrote:
> PARCP needs currently a 386... Would be great if it's useable on a XT
> with only 512KB RAM.

Why exactly would it be great?

> Any idea if this is possible?!?

Anything is possible.

Petr

**Comment by jedie** [comment]
> Why exactly would it be great?

Because PARCP is currently not useable on <368 computers, because there is no client software, isn't it?
So the other solutions are the old closed-source one line norton commander or laplink etc...

**Comment by mikrosk** [comment]
As seen for instance here: https://www.reddit.com/r/programming/comments/62sqe6/gcc_for_8088808680286_cpus/ you'd need to use a different compiler and specific compiler options. And most likely fix some issues in C source code as well. So it's a nice project but with very, very limited audience = you. ;)

**Comment by joysfera** [comment]
PARCP is about 25 years old now 

> > Why exactly would it be great?
> 
> Because PARCP is currently not useable on <368 computers

PARCP has been written as 32-bit application from the start. It makes **negative** sense to modify it for less than 32-bit CPU architecture **25 years later**. But feel free to work on that, just please understand that 8/16-bit arch patches will likely be not accepted.
